assets:
  - name: UDSM website
    uri: https://www.udsm.ac.tz/
    mimetype: webpage

  - name: CoICT website
    uri: https://www.coict.udsm.ac.tz/
    mimetype: webpage

  - name: ETE department
    uri: http://ete.udsm.ac.tz/
    mimetype: webpage
